### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by WganMe** [silasmontgomery/whmDynDns#3]
#!/bin/bash
# IPv4 address $IPv4
IPv4=$(wget -qO- http://v4.ipv6-test.com/api/myip.php)
# IPv6 address $IPv6
IPv6=$(wget -qO- http://v6.ipv6-test.com/api/myip.php)

<?php

// IPv4 address $IPv4
$IPv4 = file_get_contents('http://v4.ipv6-test.com/api/myip.php');
// IPv6 address $IPv6
$IPv6 = file_get_contents('http://v6.ipv6-test.com/api/myip.php');

**Comment by silasmontgomery** [comment]
I'm going to go ahead and close this.
