### ISSUE TITLE
Is the IpChicken example valid

### ISSUE THREAD

**Issue by lozbrown** [silasmontgomery/whmDynDns#4]
I'm attempting to configure this however i get the following error, I'm wondering if its because I need to set a differnt 

> loz@gravity:~/whmDynDns$ php whmDynDns.php
>PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in >/home/loz/whmDynDns/class.Scraper.php:37
>Stack trace:
>#0 /home/loz/whmDynDns/class.Scraper.php(25): Scraper->ScrapePage()
>#1 /home/loz/whmDynDns/whmDynDns.php(27): Scraper->GetIp()
>#2 {main}
>  thrown in /home/loz/whmDynDns/class.Scraper.php on line 37

Maybe its becuase i have this in the conf and i need to set a custom one
$websites[] = 'http://ipchicken.com';

Additionally where the config suggests "one or more as array" can the readme include an example of more as array, PHP is not usually my thing

**Comment by silasmontgomery** [comment]
Actually, this part of your post "PHP Fatal error: Uncaught Error: Call to undefined function curl_init()" makes me think you may not have php-curl extension installed. What OS are you running this on?

**Comment by lozbrown** [comment]
this is on ubuntu 16:04

**Comment by silasmontgomery** [comment]
Try: sudo apt-get install php-curl

**Comment by silasmontgomery** [comment]
Did that resolve your issue?

**Comment by lozbrown** [comment]
Sorry, I moved on to using a simpler shell script for this https://github.com/CpanelInc/cpanel-dynamicdns-tools

**Comment by silasmontgomery** [comment]
No problem
